### ISSUE TITLE
.gitignore files

### ISSUE THREAD

**Issue by kferris10** [lesliegg1/Stat532#1]
You don't actually need all the files generated by Latex when converting from .Rnw to .pdf (ex. bayeshw1-concordance.tex, bayeshw1.log, bayeshw1.synctex.gz, bayeshw1.tex, table1.aux) to make it reporducible.

If you don't want these to be in your GitHub repo, you can create a new file called .gitignore.  Git will then ignore any files that are named in the .gitignore file.  For example:

https://github.com/tdhock/animint/blob/master/.gitignore

**Comment by lesliegg1** [comment]
Thanks! That will make a it a lot cleaner.

**Comment by lesliegg1** [comment]
Figured it out, thanks!
